### ISSUE TITLE
Add build script for different distribution 

### ISSUE THREAD

**Issue by taget** [intel/rmd#26]
We need some build script to support ship RMD as

1. rpm
2. deb
3. docker image

**Comment by taget** [comment]
refer this project for building go binary deb/rpm package.
https://github.com/mh-cbon/go-github-release

**Comment by eliqiao** [comment]
@LinEricYang could you help on rpm build part?

**Comment by LinEricYang** [comment]
No problem, I can handle that part.

**Comment by taget** [comment]
Merged deb/docker build part

**Comment by LinEricYang** [comment]
RPM package build also is done.
