### ISSUE TITLE
build constraints exclude all Go files in ${GOPATH}/src/github.com/intel/rmd/lib/cache

### ISSUE THREAD

**Issue by LinEricYang** [intel/rmd#28]
When cross compile rmd in OSX platform, it failed with below error:

[INFO]  Replacing existing vendor dependencies
bash -c "./scripts/build.sh"
git commit: 7552522124e7c0679643634b6913fa6438425189
building rmd for darwin/amd64
api/v1/caches.go:12:2: build constraints exclude all Go files in ${GOPATH}/src/github.com/intel/rmd/lib/cache
make: *** [build] Error 1

Go Version: go1.9.2 darwin/amd64
OS & Version: OSX 10.13.2

It might be unnecessary to support compilation in OSX, but it would be better to specify the supported compile OS in the developer guide.

**Comment by taget** [comment]
I will take a look at it today.

**Comment by taget** [comment]
The reason is:
 https://github.com/intel/rmd/blob/master/lib/cache/cache.go#L1

Actually, RDM can only run on Linux distributions instead of OSX, so, it's reasonable that we don't support build it on `darwin`
can  a darwin go binary run on a linux host?

**Comment by taget** [comment]
Some useful digging:

1. We have specify build tag in 
https://github.com/intel/rmd/blob/master/lib/cache/cache.go#L1

Hence, on darwin, go build will report "no buildable source code in cache package"

2. in 
https://github.com/intel/rmd/blob/master/lib/proc/proc.go#L155, we involve syscall directly, darwin has no this syscall 
 ✘ taget@tagetimac  /usr/local/go/src   9:18 grep -r SYS_SCHED_GETAFFINITY *
syscall/zsysnum_linux_mipsle.go:	SYS_SCHED_GETAFFINITY      = 4240
syscall/zsysnum_linux_mips64.go:	SYS_SCHED_GETAFFINITY      = 5196
syscall/zsysnum_linux_amd64.go:	SYS_SCHED_GETAFFINITY      = 204
syscall/zsysnum_linux_mips64le.go:	SYS_SCHED_GETAFFINITY      = 5196
syscall/zsysnum_linux_mips.go:	SYS_SCHED_GETAFFINITY      = 4240
syscall/zsysnum_linux_arm.go:	SYS_SCHED_GETAFFINITY      = 242
syscall/zsysnum_linux_ppc64.go:	SYS_SCHED_GETAFFINITY      = 223
syscall/zsysnum_linux_s390x.go:	SYS_SCHED_GETAFFINITY      = 240
syscall/zsysnum_linux_arm64.go:	SYS_SCHED_GETAFFINITY      = 123
syscall/zsysnum_linux_386.go:	SYS_SCHED_GETAFFINITY      = 242
syscall/zsysnum_linux_ppc64le.go:	SYS_SCHED_GETAFFINITY      = 223

**Comment by eliqiao** [comment]
doc updates https://github.com/intel/rmd/pull/27

**Comment by LinEricYang** [comment]
It would be better to also mention it in https://github.com/intel/rmd/blob/master/docs/DeveloperQuickStart.md#build--install-rmd section.
