### ISSUE TITLE
build constraints

### ISSUE THREAD

**Issue by sn1pes** [intel/rmd#35]
hi guys, am using kali linux and trying to run following cmd: 
1 go get github.com/kbinani/screenshot && go get github.com/lxn/win
2 go install github.com/kbinani/screenshot && go install github.com/lxn/win
this are the dependencies needed to successfully build chaos framework packages
at first i set the path  in the .profile like this 
export GOPATH=~/go
export PATH=$PATH:/usr/local/go/bin:$GOPATH/bin
the it gave me this error message 
can't load package: package github.com/lxn/win: build constraints exclude all Go files in /root/go/src/github.com/lxn/win
i edited and removed  (export GOPATH=~/go) from the .profile it still gave me the same error. i edited again and removed the ( :$GOPATH/bin)  it gave me the same error 
i edited again for the last time and like this export (export PATH=$PATH:/usr/local/go/bin)
still getting the same error. i followed all the instruction from the golang site. how can i successfully fix that error.

**Comment by dakshinai** [comment]
These packages are not relevant to the rmd project.

**Comment by dakshinai** [comment]
Closing this until further information is provided.
