### ISSUE TITLE
Usage in kubernetes?

### ISSUE THREAD

**Issue by KlavsKlavsen** [intel/rmd#52]
How could this be used in kubernetes.. You write it could be run as a docker daemon.. meaning it could run as a daemonset on kubernetes I assume.. are there any recommendations to using it in kubernetes - and perhaps allocationg based on labels in kubernetes pods?

**Comment by dakshinai** [comment]
Hi Klavs, yes we are investigating an approach of deploying RMD as daemonset and using CRDs to transfer policy to RMD. Labels like RDT can help with scheduling the container requesting RDT features to the appropriate node. Do you have any use-case that you are trying to address for K8 workloads?

**Comment by KlavsKlavsen** [comment]
@dakshinai No not currently.
